-- NOTE: This schema was exported from the Heroku hosted database. If this database
--  needs to be recreated somewhere else, or to a different heroku database, change 
-- the database name, the user id, and the schema name as needed. Sincerely, Quentin

Database: d88qbo3tjfjqgk -- this is the database name. change it if needed

DROP DATABASE d88qbo3tjfjqgk;

CREATE DATABASE d88qbo3tjfjqgk
    WITH 
    OWNER = tgeuyrxmvtewzl -- This is the user id. Change it if needed
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE d88qbo3tjfjqgk TO tgeuyrxmvtewzl;

CREATE SCHEMA "public"; -- this is the schema name. Change it if needed. Also change it everywhere it appears in this file

CREATE SEQUENCE "public".recipients_id_seq START WITH 1;

CREATE SEQUENCE "public".ripple_quote_data_id_seq START WITH 1;

CREATE SEQUENCE "public".transactions_id_seq START WITH 1;

CREATE SEQUENCE "public".users_id_seq START WITH 1;

CREATE  TABLE "public".recipients ( 
	id                   integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	first_name           text  NOT NULL ,
	last_name            text  NOT NULL ,
	clabe_number         text   ,
	CONSTRAINT recipients_pkey PRIMARY KEY ( id )
 );

CREATE  TABLE "public".users ( 
	id                   integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	first_name           text   ,
	last_name            text   ,
	google_profile_id    text  NOT NULL ,
	joined               timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	CONSTRAINT users_pkey PRIMARY KEY ( id ),
	CONSTRAINT "Google profile constraint" UNIQUE ( google_profile_id ) 
 );

CREATE  TABLE "public".transactions ( 
	id                   integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	sender               integer  NOT NULL ,
	amount_usd           numeric(12,6) DEFAULT 0 NOT NULL ,
	amount_mxn           numeric(13,6) DEFAULT 0 NOT NULL ,
	recipient            integer  NOT NULL ,
	ripple_quote_id      text  NOT NULL ,
	"time"               timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	ripple_fx_rate_usdmxn numeric(8,6) DEFAULT 0  ,
	esend_fee            numeric(4,2)   ,
	esend_fx_rate_usdmxn numeric(8,6)   ,
	CONSTRAINT transactions_pkey PRIMARY KEY ( id ),
	CONSTRAINT "Ripple quote id is unique" UNIQUE ( ripple_quote_id ) ,
	CONSTRAINT "Recipient links to id in recipients table" FOREIGN KEY ( recipient ) REFERENCES "public".recipients( id )  ,
	CONSTRAINT "Sender links to id in user table" FOREIGN KEY ( sender ) REFERENCES "public".users( id )  
 );

CREATE  TABLE "public".ripple_quote_data ( 
	id                   integer GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
	ripple_quote_id      text  NOT NULL ,
	sending_fee_usd      numeric(10,8)   ,
	fx_rate_usdxrp       numeric(12,9)   ,
	xrp_fee              numeric(8,6)   ,
	receiving_fee_mxn    numeric(10,8)   ,
	fx_rate_xrpmxn       numeric(12,9)   ,
	fx_rate_usdmxn       numeric(9,6)   ,
	fk_transaction_id    integer   ,
	CONSTRAINT ripple_quote_data_pkey PRIMARY KEY ( id ),
	CONSTRAINT "fk_transaction_id is unique" UNIQUE ( fk_transaction_id ) ,
	CONSTRAINT "ripple_quote_id is unique" UNIQUE ( ripple_quote_id ) ,
	CONSTRAINT "fk_transaction_id links to id in transactions table" FOREIGN KEY ( fk_transaction_id ) REFERENCES "public".transactions( id )  ,
	CONSTRAINT "ripple_quote_id links to transactions table" FOREIGN KEY ( ripple_quote_id ) REFERENCES "public".transactions( ripple_quote_id )  
 );
